var cropLayers = {
    "BANP_R": { title: "Banana and Plantain (Average)", index: 1 },
    "BANP_I_R": { title: "Banana and Plantain (Irrigated)", index: 21 },
    "BANP_R_R": { title: "Banana and Plantain (Rainfed)", index: 38 },
    "BARL_R": { title: "Barley (Average)", index: 2 },
    "BARL_I_R": { title: "Barley (Irrigated)", index: 22 },
    "BARL_R_R": { title: "Barley (Rainfed)", index: 39 },
    "BEAN_R": { title: "Bean (Average)", index: 3 },
    "BEAN_I_R": { title: "Bean (Irrigated)", index: 23 },
    "BEAN_R_R": { title: "Bean (Rainfed)", index: 40 },
    "CASS_R": { title: "Cassava (Average)", index: 4 },
    "CASS_R_R": { title: "Cassava (Rainfed)", index: 41 },
    "COFF_R": { title: "Coffee (Average)", index: 5 },
    "COFF_I_R": { title: "Coffee (Irrigated)", index: 24 },
    "COFF_R_R": { title: "Coffee (Rainfed)", index: 42 },
    "COTT_R": { title: "Cotton (Average)", index: 6 },
    "COTT_I_R": { title: "Cotton (Irrigated)", index: 25 },
    "COTT_R_R": { title: "Cotton (Rainfed)", index: 43 },
    "GROU_R": { title: "Groundnut (Average)", index: 7 },
    "GROU_I_R": { title: "Groundnut (Irrigated)", index: 26 },
    "GROU_R_R": { title: "Groundnut (Rainfed)", index: 44 },
    "MAIZ_R": { title: "Maize (Average)", index: 8 },
    "MAIZ_I_R": { title: "Maize (Irrigated)", index: 27 },
    "MILL_R_R": { title: "Maize (Rainfed)", index: 45 },
    "MILL_R": { title: "Millet (Average)", index: 9 },
    "MILL_I_R": { title: "Millet (Irrigated)", index: 28 },
    "MILL_R_R": { title: "Millet (Rainfed)", index: 46 },
    "OFIB_R": { title: "Other Fiber (Average)", index: 10 },
    "OFIB_R_R": { title: "Other Fiber (Rainfed)", index: 47 },
    "OOIL_R": { title: "Other Oil (Average)", index: 11 },
    "OOIL_R_R": { title: "Other Oil (Rainfed)", index: 48 },
    "OPUL_R": { title: "Other Pulses (Average)", index: 12 },
    "OPUL_I_R": { title: "Other Pulses (Irrigated)", index: 29 },
    "OPUL_R_R": { title: "Other Pulses (Rainfed)", index: 49 },
    "POTA_R": { title: "Potato (Average)", index: 13 },
    "POTA_I_R": { title: "Potato (Irrigated)", index: 30 },
    "POTA_R_R": { title: "Potato (Rainfed)", index: 50 },
    "RICE_R": { title: "Rice (Average)", index: 14 },
    "RICE_I_R": { title: "Rice (Irrigated)", index: 31 },
    "RICE_R_R": { title: "Rice (Rainfed)", index: 51 },
    "SORG_R": { title: "Sorghum (Average)", index: 15 },
    "SORG_I_R": { title: "Sorghum (Irrigated)", index: 32 },
    "SORG_R_R": { title: "Sorghum (Rainfed)", index: 52 },
    "SOYB_R": { title: "Soybean (Average)", index: 16 },
    "SOYB_I_R": { title: "Soybean (Irrigated)", index: 33 },
    "SOYB_R_R": { title: "Soybean (Rainfed)", index: 53 },
    "SUGC_R": { title: "Sugarcane (Average)", index: 17 },
    "SUGC_I_R": { title: "Sugarcane (Irrigated)", index: 34 },
    "SUGC_R_R": { title: "Sugarcane (Rainfed)", index: 54 },
    "SWPY_R": { title: "Sweet Potato and Yam (Average)", index: 18 },
    "SWPY_I_R": { title: "Sweet Potato and Yam (Irrigated)", index: 35 },
    "SWPY_R_R": { title: "Sweet Potato and Yam (Rainfed)", index: 55 },
    "WHEA_R": { title: "Wheat (Average)", index: 19 },
    "WHEA_I_R": { title: "Wheat (Irrigated)", index: 36 },
    "WHEA_R_R": { title: "Wheat (Rainfed)", index: 56 },
};